name: Run YouTube to Dropbox Script

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours (4 times/day)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          pip install yt-dlp dropbox

      - name: Run the script
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          YOUTUBE_CHANNEL_URL: ${{ secrets.YOUTUBE_CHANNEL_URL }}
          DROPBOX_UPLOAD_PATH: ${{ secrets.DROPBOX_UPLOAD_PATH }}
          HASHTAGS: ${{ secrets.HASHTAGS }}
          COOKIES_FILE_URL: ${{ secrets.COOKIES_FILE_URL }}  # Add this line to define the missing variable
        run: python main.py
